# Generated by Django 4.1.5 on 2023-02-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompanyParser', '0002_item_curent_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ActivityCompany',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='item',
            name='NameCompany',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='item',
            name='SiteCompany',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='item',
            name='cityCompany',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='item',
            name='notification',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
